[versions]
compileSdkVersion = "36"
minSdkVersion = "24"
targetSdkVersion = "35"

gradleVersion = "8.13.0"
kotlin_version = '2.1.20'
kotlinx_version = '1.10.2'

desugar_version = '2.1.5'

firebase_version = '34.4.0'
firebaseCrashlyticsGradleVersion = "3.0.6"
googleServicesVersion = "4.4.4"
play_services_wearable_version = "19.0.0"
app_update_ktx_version = "2.1.0"

activity_version = '1.11.0'
annotation_version = "1.9.1"
appcompat_version = '1.7.1'
constraintlayout_version = '2.2.1'
core_version = '1.17.0'
fragment_version = '1.8.9'
lifecycle_version = '2.9.4'
preference_version = '1.2.1'
recyclerview_version = '1.4.0'
recyclerview_selection_version = "1.2.0"
coresplash_version = '1.0.1'
work_version = '2.11.0'
navigation_version = '2.9.5'
datastore_version = '1.1.7'
media_version = "1.7.1"
palette_version = "1.0.0"

test_core_version = '1.7.0'
test_runner_version = '1.7.0'
test_rules_version = '1.7.0'
junit_version = '1.3.0'
androidx_truth_version = '1.7.0'
google_truth_version = '1.4.5'

material_version = '1.14.0-alpha06'
material_compose_version = '1.5.0-alpha06'

compose_bom_version = '2025.10.00'
compose_compiler_version = '1.5.15'

wearableVersion = "2.9.0"
wear_version = "1.3.0"
wear_ongoing_version = "1.1.0"
wear_phone_interactions_version = "1.1.0"
wear_remote_interactions_version = "1.1.0"
wear_tooling_preview_version = "1.0.0"
reorderable_version = "3.0.0"

wear_compose_version = '1.5.4'
wear_tiles_version = '1.5.0'
wear_watchface_version = '1.2.1'
horologist_version = '0.7.15'
accomapnist_version = '0.37.3'
wear_protolayout_version = "1.3.0"

gson_version = '2.13.2'
timber_version = '5.0.1'

# Shizuku
shizuku_version = '13.1.5'
refine_version = '4.4.0'

libsu_version = "3.1.2"
dexmaker_version = "2.28.6"
hiddenapibypassVersion = "6.1"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accomapnist_version" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation_version" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose_compiler_version" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material_compose_version" }
androidx-compose-material-icons-extended-android = { module = "androidx.compose.material:material-icons-extended-android" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
wear-tiles-tooling-preview = { module = "androidx.wear.tiles:tiles-tooling-preview", version.ref = "wear_tiles_version" }
androidx-watchface-complications-data = { module = "androidx.wear.watchface:watchface-complications-data", version.ref = "wear_watchface_version" }
refine-annotation = { module = "dev.rikka.tools.refine:annotation", version.ref = "refine_version" }
refine-annotation-processor = { module = "dev.rikka.tools.refine:annotation-processor", version.ref = "refine_version" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypassVersion" }
horologist-audio-ui-material3 = { module = "com.google.android.horologist:horologist-audio-ui-material3", version.ref = "horologist_version" }
libsu-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu_version" }
refine-runtime = { module = "dev.rikka.tools.refine:runtime", version.ref = "refine_version" }
shizuki-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku_version" }
shizuki-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku_version" }
compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin_version" }
wear-compose-ui-tooling = { module = "androidx.wear.compose:compose-ui-tooling", version.ref = "wear_compose_version" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradleVersion" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServicesVersion" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
horologist-compose-tools = { module = "com.google.android.horologist:horologist-compose-tools", version.ref = "horologist_version" }
horologist-tiles = { module = "com.google.android.horologist:horologist-tiles", version.ref = "horologist_version" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin_version" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_version" }
test-core = { module = "androidx.test:core", version.ref = "test_core_version" }
test-runner = { module = "androidx.test:runner", version.ref = "test_runner_version" }
test-rules = { module = "androidx.test:rules", version.ref = "test_rules_version" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit_version" }
androidx-truth = { module = "androidx.test.ext:truth", version.ref = "androidx_truth_version" }
google-truth = { module = "com.google.truth:truth", version.ref = "google_truth_version" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx_version" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx_version" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx_version" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core_version" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment_version" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference_version" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle_version" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle_version" }
wearable = { module = "com.google.android.wearable:wearable", version.ref = "wearableVersion" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work_version" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coresplash_version" }
play-services-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "play_services_wearable_version" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "app_update_ktx_version" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase_version" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-config = { module = "com.google.firebase:firebase-config" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat_version" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout_version" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview_version" }
recyclerview-selection = { module = "androidx.recyclerview:recyclerview-selection", version.ref = "recyclerview_selection_version" }
media = { module = "androidx.media:media", version.ref = "media_version" }
material = { module = "com.google.android.material:material", version.ref = "material_version" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber_version" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson_version" }
dexmaker = { module = "com.linkedin.dexmaker:dexmaker", version.ref = "dexmaker_version" }
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wear_compose_version" }
wear-compose-material3 = { module = "androidx.wear.compose:compose-material3", version.ref = "wear_compose_version" }
wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wear_compose_version" }
wear-protolayout-material3 = { module = "androidx.wear.protolayout:protolayout-material3", version.ref = "wear_protolayout_version" }
horologist-compose-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologist_version" }
horologist-media-ui-material3 = { module = "com.google.android.horologist:horologist-media-ui-material3", version.ref = "horologist_version" }
wear-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "wear_tiles_version" }
wear-tiles-testing = { module = "androidx.wear.tiles:tiles-testing", version.ref = "wear_tiles_version" }
wear-tiles-renderer = { module = "androidx.wear.tiles:tiles-renderer", version.ref = "wear_tiles_version" }
wear-tiles-tooling = { module = "androidx.wear.tiles:tiles-tooling", version.ref = "wear_tiles_version" }
wear-watchface-complications-data-source-ktx = { module = "androidx.wear.watchface:watchface-complications-data-source-ktx", version.ref = "wear_watchface_version" }
palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "palette_version" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity_version" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose_bom_version" }
navigation-runtime-ktx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigation_version" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore_version" }
wear = { module = "androidx.wear:wear", version.ref = "wear_version" }
wear-ongoing = { module = "androidx.wear:wear-ongoing", version.ref = "wear_ongoing_version" }
wear-phone-interactions = { module = "androidx.wear:wear-phone-interactions", version.ref = "wear_phone_interactions_version" }
wear-remote-interactions = { module = "androidx.wear:wear-remote-interactions", version.ref = "wear_remote_interactions_version" }
wear-tooling-preview = { module = "androidx.wear:wear-tooling-preview", version.ref = "wear_tooling_preview_version" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable_version" }

[plugins]
